server:
  port: 7003

spring:
  application:
    name: eureka-server-peer3

eureka:
  instance:
    hostname: peer3
  client:
    #表示是否将自己注册到Eureka Server，默认为true。
    register-with-eureka: false
    #表示是否从Eureka Server获取注册信息，默认为true。
    fetch-registry: false
    service-url:
      #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。多个地址可使用 , 分隔。
      defaultZone: http://peer1:7001/eureka/,http://peer2:7002/eureka/
