server:
  port: 7001

spring:
  application:
    name: eureka-server

eureka:
  instance:
    #主机名，会在控制页面中显示
    hostname: localhost
  client:
    #通过eureka.client.registerWithEureka：false和fetchRegistry：false来表明自己是一个eureka server.
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
