server:
  servlet:
    context-path: /api
spring:
  application:
    name: api-server
  profiles:
    active: dev
  jackson:
    date-format:  yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    consul:
      enabled: false                    #是否启用
      host: localhost
      port: 8500
      discovery:
        service-name: apiServer         #注册到consul的服务名称


