server:
  port: 8080

logging:
  config: classpath:logback-dev.xml

spring:
  redis:
    database: 0                       # Redis数据库索引（默认为0）
    host: 114.55.242.55
    port: 6379
    password: 'redis2915Qaz!'
    timeout:  1000                    # 连接超时时间（毫秒）
    lettuce:
      pool:
        max-active: 8                 # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-wait: -1                  # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-idle: 8                   # 连接池中的最大空闲连接 默认 8
        min-idle: 0                   # 连接池中的最小空闲连接 默认 0
  
alipay:
  default:
    appId: 111111
    appPrivateKey: xxxxxx
    charset: UTF-8
    alipayPublicKey: xxxxxx
    serverUrl: https://openapi.alipay.com/gateway.do
    notifyUrl: xxxxxx
  deposit:
    appId: 222222
    appPrivateKey: xxxxxx
    charset: UTF-8
    alipayPublicKey: xxxxxx
    serverUrl: https://openapi.alipay.com/gateway.do
    notifyUrl: xxxxxx

wechatpay:
  default:
    apiAppId: 333333
    apiMchId: 333333
    apiKey: xxxxxx
    certPath: d/path/to/apiclientCert.p12
    notifyUrl: xxxxxx
  deposit:
    apiAppId: 444444
    apiMchId: 444444
    apiKey: xxxxxx
    certPath: d/path/to/apiclientCert.p12
    notifyUrl: xxxxxx
