server:
  port: 8080

logging:
  config: classpath:logback-dev.xml

alipay:
  default:
    appId: 123456
    appPrivateKey: xxxxxx
    charset: 111
    alipayPublicKey: xxx
    serverUrl: https://openapi.alipay.com/gateway.do
    notifyUrl: baidu
  deposit:
    appId: 123456
    appPrivateKey: xxxxxx
    charset: 111
    alipayPublicKey: xxx
    serverUrl: https://openapi.alipay.com/gateway.do
    notifyUrl: baidu

wechatpay:
  default:
    appId: 123456
    mchId: xxxxxx
    appKey: 111
    certPath: d/path/to/apiclientCert.p12
    serverUrl: https://openapi.alipay.com/gateway.do
    notifyUrl: baidu
  deposit:
    appId: 123456
    mchId: xxxxxx
    appKey: 111
    certPath: d/path/to/apiclientCert.p12
    serverUrl: https://openapi.alipay.com/gateway.do
    notifyUrl: baidu
